entities:
  Rama:
    aliases:
      - Sri Rama
      - Rama
      - Ramudu
      - Raghunandana
      - Raghuvara
      - Dasharatha Rama
      - Sitapati
      - Raghava
      - Kakutstha

  Sita:
    aliases:
      - Sita
      - Sita Devi
      - Janaki
      - Maithili
      - Vaidehi
      - Janaka's daughter

  Lakshmana:
    aliases:
      - Lakshmana
      - Saumitri
      - Rama's younger brother

  Vishvamitra:
    aliases:
      - Vishvamitra
      - Kaushika

  Hanuman:
    aliases:
      - Hanuman
      - Anjaneya
      - Maruti
      - son of Vayu

  Ravana:
    aliases:
      - Ravana
      - Lord of Lanka
      - Dashakantha
